#!/bin/sh

FEEDEOBOT_HOME=/root/feedeobot

git=`which git`

cd $FEEDEOBOT_HOME

$git remote update > /dev/null 2>&1 && \
$git status -uno | \
grep -q "Your branch is behind" && \
$git reset --hard origin/master

return "$?"
