#!/usr/bin/env node

process.on('SIGINT', function() {
    raspbot.stop(function() {
        process.exit(0);
    });
});

process.once('SIGUSR2', function() {
    raspbot.reload(function() {
        process.kill(process.pid, 'SIGUSR2');
    });
});

process.on('exit', function() {
});

process.on('uncaughtException', function(error) {
    raspbot.error(error);
})

var raspbot = require('./raspbot.js');

raspbot.start(function() {
});
